import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className} border`}>
        <h1 className="text-7xl pt-32 pb-8 text-center font-black uppercase leading-snug">
          Start Your
          <br />
          E-commerce project
        </h1>
        <div className="flex justify-center">
          <p className="text-center max-w-6xl pb-32">
            Introducing our Next.js e-commerce website template – the perfect
            starting point for building your online store. We've included all
            the{" "}
            <b>
              essential pages, from product listings to checkout, as well as
              popular dependencies like React-Icons and Tailwind CSS
            </b>{" "}
            to make your development process smoother. With everything you need
            in one place, you can jump right in and start building
          </p>
        </div>
      </main>
    </>
  );
}
